### PR TITLE
Devtools, DX update: Replaced discontinued node-sass

### PR DESCRIPTION
**Pull request by WesWedding**
Node-sass was recently archived on Github and directs people to use Dart Sass (known as simply `sass`). See: https://sass-lang.com/blog/node-sass-is-end-of-life/

This does change the SASS output slightly; no more strange brackets at the end of lines and excess white space inherited from the SASS.

Exmaple:
```
      .sta.sheet.actor .track .bar .box.rep.selected {
        background-color: #CC2233;
        color: #000000; }
```
became
```
.sta.sheet.actor .track .bar .box.stress.selected {
  background-color: #1111EE;
  color: #FEFEFE;
}
```

I also added a note about what to do with foundryconfig.json; it's a pretty minor speedbump but still nice to have it documented.

Also added a missing dev dependency for linting.

### CODE REVIEW

**Comment by WesWedding** [comment]
I've also updated Gulp so that it updates that sta.css file in the repo; it seems like a Developer Experience win because you can use Git to see how the CSS changes in response to SCSS changes. 

Otherwise I think maybe removing the file completely is in order, it lead me down a wild goose chase trying to figure out why my SASS changes weren't being reflected in the CSS file.

**Comment by tokeidlom** [comment]
I don't have access to the Dev tools to test this change, so will leave it for Mike to approve & merge in the case. However, it appears like sensible changes.

**Comment by mkscho63** [comment]
Yeah the .css file is not suppose to be in source. We should remove it back out again. It must have snuck in at some point. Since it's a derived file it should only be generated when running a build.

**Comment by mkscho63** [comment]
I can remove the file once I get back home from gencon after this weekend. If you are able to remove it before then though I can review and approve this PR. Either way works I think.

**Comment by WesWedding** [comment]
sta.css is un-tracked and .gitignored correctly again.

**Review by mkscho63 — APPROVED** [review]

**Pull request merged**
